package com.example.starfood.datamodel.lottery

data class Product(
    val eightthPrize: String,
    val eleventhPrize: String,
    val fifteenthPrize: String,
    val fifthPrize: String,
    val firstPrize: String,
    val fourteenthPrize: String,
    val fourthPrize: String,
    val id: String,
    val ninethPrize: String,
    val secondPrize: String,
    val seventhPrize: String,
    val showeightthPrize: String,
    val showeleventhPrize: String,
    val showfifteenthPrize: String,
    val showfifthPrize: String,
    val showfirstPrize: String,
    val showfourteenthPrize: String,
    val showfourthPrize: String,
    val showninethPrize: String,
    val showsecondPrize: String,
    val showseventhPrize: String,
    val showsixteenthPrize: String,
    val showsixthPrize: String,
    val showteenthPrize: String,
    val showtherteenthPrize: String,
    val showthirdPrize: String,
    val showtwelvthPrize: String,
    val sixteenthPrize: String,
    val sixthPrize: String,
    val teenthPrize: String,
    val therteenthPrize: String,
    val thirdPrize: String,
    val timestam: String,
    val twelvthPrize: String
)